id: NCHLOD
name: nepalCulturalHeritageLinkedOpenData
description: "A LinkML schema implementing CIDOC-CRM-aligned classes, event-centric patterns, and provenance for Nepal cultural heritage linked open data."
version: "2025-11-22"
imports:
  - linkml:types

prefixes:
  crm: "http://www.cidoc-crm.org/cidoc-crm/"
  linkml: "https://w3id.org/linkml/"
  nchlod: "https://cair-nepal.org/nchlod/"
  prov: "http://www.w3.org/ns/prov#"
  schema: "http://schema.org/"

default_prefix: crm



classes:

  E18_Physical_Thing:
    class_uri: crm:E18_Physical_Thing
    description: "Superclass for all physical things including monuments, artefacts, buildings and parts."
    slots:
      - has_identifier
      - has_title
      - has_type
      - has_material
      - has_dimension
      - current_owner
      - former_owner
      - has_provenance

  E22_Human_Made_Object:
    is_a: E18_Physical_Thing
    description: "Physical objects created by humans (artworks, artifacts, tools)."

  E12_Production:
    description: "The beginning of existence of a physical thing (production event)." 
    slots:
      - produced_object
      - carried_out_by
      - took_place_at
      - has_time_span
      - has_provenance

  E5_Event:
    description: "General event (change of state). Use sub-classes for specificity."
    slots:
      - took_place_at
      - has_time_span
      - carried_out_by
      - has_provenance

  E7_Activity:
    is_a: E5_Event
    description: "Action or process that results in a change of state."
    slots:
      - used_material
      - produced_object

  E6_Destruction:
    is_a: E5_Event
    description: "Event resulting in destruction of an object."
    slots:
      - destroyed_object

  E11_Modification:
    is_a: E5_Event
    description: "An event that modifies an object."
    slots:
      - modified_object
      - modification_note

  E10_Transfer_of_Custody:
    is_a: E5_Event
    description: "Event representing custody transfer."
    slots:
      - transferred_object
      - from_actor
      - to_actor

  E13_Attribute_Assignment:
    is_a: E5_Event
    description: "Record of an assigned attribute (deprecated/previous values, contested assertions)."
    slots:
      - assigned_attribute
      - assigned_by
      - assigned_value
      - has_provenance

  E31_Document:
    description: "Document, record or archival source that provides evidence."
    slots:
      - title
      - author
      - date
      - url
      - license
      - has_provenance

  E33_Linguistic_Object:
    is_a: E31_Document
    description: "Statements, inscriptions, or textual objects."
    slots:
      - written_in_language

  E52_Time_Span:
    description: "A time-span object (has beginning and end)."
    slots:
      - has_beginning
      - has_end

  E92_Spatetime_Volume:
    description: "Spatial and temporal extent used for precise spatio-temporal modelling (site extents, archaeological layers)."
    slots:
      - has_geometry
      - has_timespan

  E53_Place:
    description: "Location in the natural or built environment."
    slots:
      - name
      - latitude
      - longitude
      - geometry
      - gazetteer_id
      - has_provenance

  E21_Person:
    description: "Individual human actor."
    slots:
      - has_name
      - birth_event
      - death_event
      - has_provenance

  E39_Actor:
    description: "Actor: individuals, groups or organisations involved in events."
    slots:
      - participated_in
      - has_identifier
      - name

  E73_Information_Object:
    description: "Concepts, schemes, records, and textual objects carrying information."
    slots:
      - contains_information
      - language

  E55_Type:
    description: "Types from external vocabularies (AAT, local taxonomies)."
    slots:
      - referenced_in

  E42_Identifier:
    description: "Identifier assigned to an entity (value + optional assigner)."
    slots:
      - identifier_value
      - identifier_type
      - assigned_by
      - assignment_event

  E16_Measurement:
    description: "Measurement event/value (dimensions, weight, dating)."
    slots:
      - measured_object
      - measurement_unit
      - measurement_value
      - measurement_method
      - has_time_span

  E14_Condition_Assessment:
    description: "Conservation assessment of physical state of an object."
    slots:
      - assessed_object
      - assessment_date
      - assessment_note
      - assessor

  E30_Right:
    description: "Legal rights or custodial claims associated with an object."
    slots:
      - right_holder
      - right_type
      - valid_from
      - valid_to

  E29_Design_or_Procedure:
    description: "Designs, procedures or protocols (restoration workflows, ritual procedures)."
    slots:
      - procedure_name
      - description

  DataProvenance:
    description: "Digital provenance metadata for dataset records (PROV-compatible)."
    slots:
      - recorded_by
      - record_date
      - source_document
      - derived_from
      - license
      - confidence
      - provenance_note

  Contributor:
    is_a: E39_Actor
    description: "Project contributor (subclass of E39_Actor)."
    slots:
      - role
      - affiliation
      - contribution_date
      - email
      - start_date
      - end_date

  Place:  
    is_a: E53_Place
    description: "Project place specialization with common slots."


slots:
  
  name:
    uri: schema:name
    description: "Human-readable name or title."
    range: string

  title:
    uri: schema:title
    description: "Document or object title."
    range: string

  has_title:
    description: "Title or appellation for an object."
    domain: E18_Physical_Thing
    range: string
    multivalued: true

  has_name:
    description: "Name of a person or actor."
    domain: [E21_Person, E39_Actor]
    range: string

  has_identifier:
    description: "Identifier(s) for an entity (URI, catalog number, local id)."
    domain: [E18_Physical_Thing, E39_Actor, E31_Document, E5_Event]
    range: E42_Identifier
    multivalued: true

  identifier_value:
    description: "Literal identifier value (string)."
    domain: E42_Identifier
    range: string

  identifier_type:
    description: "Identifier type or vocabulary (e.g., ISBN, inventoryNo)."
    domain: E42_Identifier
    range: E55_Type

  assigned_by:
    description: "Actor who assigned an identifier or attribute."
    domain: E42_Identifier
    range: E39_Actor

  assignment_event:
    description: "Event recording the assignment of an identifier."
    domain: E42_Identifier
    range: E13_Attribute_Assignment

  has_type:
    description: "Type classification for an entity (maps to E55 Type)."
    domain: [E18_Physical_Thing, E73_Information_Object]
    range: E55_Type
    multivalued: true

  has_material:
    description: "Material(s) composing an object (link to E57 Material)."
    domain: E18_Physical_Thing
    range: E57_Material
    multivalued: true

  has_dimension:
    description: "Dimension object or measurement for an item."
    domain: E18_Physical_Thing
    range: E54_Dimension
    multivalued: true

  has_provenance:
    description: "Attach DataProvenance records to objects/events/documents."
    domain: [E18_Physical_Thing, E22_Human_Made_Object, E5_Event, E31_Document]
    range: DataProvenance
    multivalued: true

  recorded_by:
    description: "Actor who recorded or digitized the record."
    domain: DataProvenance
    range: E39_Actor

  record_date:
    description: "Date when the record was created (digitization/ingest)."
    domain: DataProvenance
    range: datetime

  source_document:
    description: "Source document (E31 Document) used as evidence."
    domain: DataProvenance
    range: E31_Document

  derived_from:
    description: "Information object derived from another information object."
    domain: DataProvenance
    range: E73_Information_Object

  license:
    description: "License or rights statement (dataset or record level)."
    domain: [DataProvenance, E31_Document]
    range: string

  confidence:
    description: "Confidence score for an asserted statement (0.0-1.0)."
    domain: DataProvenance
    range: float

  provenance_note:
    description: "Free text provenance notes or evidence summary."
    domain: DataProvenance
    range: string

  carried_out_by:
    description: "Actor(s) who carried out an event. (P14_carried_out_by)"
    domain: E5_Event
    range: E39_Actor
    multivalued: true

  took_place_at:
    description: "Place where an event took place. (P7_took_place_at)"
    domain: E5_Event
    range: E53_Place
    multivalued: true

  has_time_span:
    description: "Time-span for events or measurements (P4_has_time-span)."
    domain: [E5_Event, E16_Measurement, E92_Spatetime_Volume]
    range: E52_Time_Span

  has_beginning:
    description: "Start datetime of a timespan."
    domain: E52_Time_Span
    range: datetime

  has_end:
    description: "End datetime of a timespan."
    domain: E52_Time_Span
    range: datetime

  produced_object:
    description: "Object produced by a production event (P108_has_produced)."
    domain: E12_Production
    range: E22_Human_Made_Object
    multivalued: true

  destroyed_object:
    description: "Object destroyed in a destruction event."
    domain: E6_Destruction
    range: E18_Physical_Thing

  modified_object:
    description: "Object modified in a modification event."
    domain: E11_Modification
    range: E18_Physical_Thing

  transferred_object:
    description: "Object transferred during custody transfer."
    domain: E10_Transfer_of_Custody
    range: E18_Physical_Thing

  from_actor:
    description: "Actor transferring custody FROM."
    domain: E10_Transfer_of_Custody
    range: E39_Actor

  to_actor:
    description: "Actor transferring custody TO."
    domain: E10_Transfer_of_Custody
    range: E39_Actor

  used_material:
    description: "Material used during an activity."
    domain: E7_Activity
    range: E57_Material

  measured_object:
    description: "Object the measurement pertains to."
    domain: E16_Measurement
    range: E18_Physical_Thing

  measurement_unit:
    description: "Unit of measurement (E58 Measurement Unit)."
    domain: E16_Measurement
    range: E58_Measurement_Unit

  measurement_value:
    description: "Numeric value of a measurement."
    domain: E16_Measurement
    range: float

  assessment_date:
    description: "Date of condition assessment."
    domain: E14_Condition_Assessment
    range: datetime

  assessment_note:
    description: "Textual note about condition or conservation findings."
    domain: E14_Condition_Assessment
    range: string

  assessor:
    description: "Actor performing the condition assessment."
    domain: E14_Condition_Assessment
    range: E39_Actor

  has_coordinates:
    description: "Legacy coordinates field (kept for compatibility). Prefer latitude/longitude or geometry."
    domain: E53_Place
    range: string

  latitude:
    description: "Latitude of a place (decimal degrees)."
    domain: E53_Place
    range: float

  longitude:
    description: "Longitude of a place (decimal degrees)."
    domain: E53_Place
    range: float

  geometry:
    description: "GeoJSON geometry for complex extents (Polygon, MultiPolygon, Point)."
    domain: E53_Place
    range: string

  gazetteer_id:
    description: "External gazetteer identifier (TGN, GeoNames, Wikidata)."
    domain: E53_Place
    range: string

  current_owner:
    description: "Current custodial actor for an object."
    domain: E18_Physical_Thing
    range: E39_Actor

  former_owner:
    description: "Prior custodial actor for an object."
    domain: E18_Physical_Thing
    range: E39_Actor
    multivalued: true

  role:
    description: "Role of a contributor in the project (curator, digitizer, researcher)."
    domain: Contributor
    range: string

  affiliation:
    description: "Organization affiliation for a contributor."
    domain: Contributor
    range: string

  contribution_date:
    description: "Date of a specific contribution."
    domain: Contributor
    range: datetime

  email:
    description: "Email of contributor."
    domain: Contributor
    range: string

  start_date:
    description: "Contributor start date."
    domain: Contributor
    range: datetime

  end_date:
    description: "Contributor end date."
    domain: Contributor
    range: datetime


  E57_Material:
    description: "Material type (can be linked to AAT or local lists)."
    slots:
      - referenced_in

  E54_Dimension:
    description: "Dimension record (length, height, depth, weight)."
    slots:
      - has_unit
      - has_value

  E56_Language:
    description: "Language (ISO 639-3 or external URI)."
    slots:
      - spoken_by

  E58_Measurement_Unit:
    description: "Units such as cm, in, kg."
    slots:
      - unit_of

  E98_Currency:
    description: "Currency used in monetary records."

  has_value:
    description: "Numeric value."
    range: float

  has_unit:
    description: "The unit of the measurement."
    range: E58_Measurement_Unit

  url:
    description: "Web link to the document."
    range: uri

  right_holder:
    description: "The actor holding the right."
    range: E39_Actor

  has_unit:
    domain: [E54_Dimension, E16_Measurement]
    range: E58_Measurement_Unit
  
  has_value:
    domain: [E54_Dimension, E16_Measurement]
    range: float
    
  measurement_method:
    domain: E16_Measurement
    range: E55_Type  # e.g., "Carbon dating", "Laser scanning"