#!/usr/bin/env python3
"""Migrate the demonstrator ABox and 32-CQ query file to the 0.1.0-alpha.5
vocabulary. Every `hg:<name>` token is mapped to the slot_uri/class_uri
declared in HeritageGraph_fixed.yaml (so the data matches the published RDF
semantics); renamed/deleted terms are handled by an explicit table; enum
values are serialized as literals (LinkML enum semantics)."""
from __future__ import annotations
import re
from pathlib import Path
from linkml_runtime import SchemaView

ROOT = Path(__file__).resolve().parents[1]
sv = SchemaView(str(ROOT / "ontology" / "HeritageGraph.yaml"))

mapping: dict[str, str] = {}
for name, s in sv.all_slots().items():
    if s.slot_uri:
        mapping[name] = str(s.slot_uri).replace("heritageGraph:", "hg:")
for name, c in sv.all_classes().items():
    if c.class_uri:
        mapping[name] = str(c.class_uri).replace("heritageGraph:", "hg:")

RENAMES = {
    "HeritageAssertion": "Assertion", "LivingGoddessTenure": "KumariTenure",
    "LivingGoddessRetirement": "KumariRetirementEvent",
    "LivingGoddessSelection": "KumariSelectionEvent",
    "has_provenance_assertion": "has_assertion",
    "asserts_about_entity": "asserts_about", "subject_entity": "asserts_about",
    "asserted_value": "assertion_content",
    "has_retirement_event": "retired_through", "results_in_role": "confers_role",
}
DIRECT = {  # old tokens with no current slot: map straight to URIs
    "was_attributed_to_agent": "prov:wasAttributedTo",
    "was_derived_from_source": "prov:wasDerivedFrom",
}
# Enum values serialize as their `meaning:` URI when one is declared,
# otherwise as a plain literal (LinkML enum semantics).
ENUM_VALUES: dict[str, str] = {}
for e in sv.all_enums().values():
    for vname, pv in (e.permissible_values or {}).items():
        ENUM_VALUES[vname] = str(pv.meaning) if pv.meaning else f'"{vname}"'

unmapped: set[str] = set()
def sub(m: re.Match) -> str:
    tok = m.group(1)
    if tok in DIRECT:
        return DIRECT[tok]
    if tok in ENUM_VALUES and tok not in sv.all_classes():
        return ENUM_VALUES[tok]
    tok = RENAMES.get(tok, tok)
    if tok in mapping:
        return mapping[tok]
    unmapped.add(tok)
    return "hg:" + tok

TTL_PREFIXES = """@prefix aat: <http://vocab.getty.edu/aat/> .
@prefix crminf: <http://www.ics.forth.gr/isl/CRMinf/> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix schema: <http://schema.org/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
"""
JOBS = [
    ("examples/kathmandu-mini-abox.ttl", "examples/kathmandu-mini-abox-alpha5.ttl", True),
    ("examples/queries/cq-abox-32.rq", "examples/queries/cq-abox-32-alpha5.rq", False),
]
for src_rel, dst_rel, is_ttl in JOBS:
    text = (ROOT / src_rel).read_text(encoding="utf-8")
    out = re.sub(r"\bhg:([A-Za-z_][A-Za-z0-9_]*)\b", sub, text)
    if is_ttl:
        out = out.replace("@prefix crm:", TTL_PREFIXES + "@prefix crm:", 1)
        out = ("# MIGRATED to HeritageGraph 0.1.0-alpha.5 (generated by "
               "scripts/migrate_abox_alpha5.py; do not edit by hand).\n") + out
    else:
        blocks = re.split(r"(?=^# CQ\d+:)", out, flags=re.M)
        fixed = []
        for b in blocks:
            if b.startswith("# CQ"):
                for pfx, uri in [("crm", "http://www.cidoc-crm.org/cidoc-crm/"),
                                 ("crminf", "http://www.ics.forth.gr/isl/CRMinf/"),
                                 ("prov", "http://www.w3.org/ns/prov#"),
                                 ("rdfs", "http://www.w3.org/2000/01/rdf-schema#")]:
                    if re.search(r"\b" + pfx + r":", b) and ("PREFIX " + pfx + ":") not in b:
                        lines = b.split("\n")
                        idx = max([i for i, l in enumerate(lines) if l.startswith("PREFIX")] or [0])
                        lines.insert(idx + 1, f"PREFIX {pfx}: <{uri}>")
                        b = "\n".join(lines)
            fixed.append(b)
        out = ("# MIGRATED to HeritageGraph 0.1.0-alpha.5 (generated by "
               "scripts/migrate_abox_alpha5.py). Run with evaluation/run_abox_cq32.py.\n") + "".join(fixed)
    (ROOT / dst_rel).write_text(out, encoding="utf-8")
    print("wrote", dst_rel)
print("unmapped tokens (left as hg:):", sorted(unmapped) or "NONE")
